import {Routes, Route, useRoutes, BrowserRouter } from "react-router-dom";
import './App.css';
import HomeComponent from "./components/HomeComponent";
import ReposComponent from "./components/ReposComponent";
import RepositoryDetails from "./components/RepositoryDetails";
import NavBar from "./NavBar";

function App() {
  return (
    <div>
    <BrowserRouter >
    <NavBar/>
      <Routes>
      <Route path="/home/" element={<HomeComponent 
                        name={data.name}
                        public_repos={data.public_repos}
                        followers={data.followers}
                        following={data.following}
                        avatar_url ={data.avatar_url}/>}/>
      <Route path="/" element={<HomeComponent 
                        name={data.name}
                        public_repos={data.public_repos}
                        followers={data.followers}
                        following={data.following}
                        avatar_url ={data.avatar_url}/>}/>

      <Route path="/repos" element={
                        <ReposComponent repos={repos}
                        />}/>

      <Route path="/repos/:repositoryId" element={<RepositoryDetails 
                       repos={repos}/>}/>

      </Routes> 
      </BrowserRouter >            

     </div>
  );


  

}

const data = {
  "login": "Ale652",
  "id": 8323240,
  "node_id": "MDQ6VXNlcjgzMjMyNDA=",
  "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Ale652",
  "html_url": "https://github.com/Ale652",
  "followers_url": "https://api.github.com/users/Ale652/followers",
  "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
  "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
  "organizations_url": "https://api.github.com/users/Ale652/orgs",
  "repos_url": "https://api.github.com/users/Ale652/repos",
  "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Ale652/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 7,
  "public_gists": 0,
  "followers": 0,
  "following": 5,
  "created_at": "2014-07-31T19:13:59Z",
  "updated_at": "2022-02-28T07:02:27Z"
};


const repos = [
  {
    "id": 481343321,
    "node_id": "R_kgDOHLC3WQ",
    "name": "CV-APP",
    "full_name": "Ale652/CV-APP",
    "private": false,
    "owner": {
      "login": "Ale652",
      "id": 8323240,
      "node_id": "MDQ6VXNlcjgzMjMyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ale652",
      "html_url": "https://github.com/Ale652",
      "followers_url": "https://api.github.com/users/Ale652/followers",
      "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
      "organizations_url": "https://api.github.com/users/Ale652/orgs",
      "repos_url": "https://api.github.com/users/Ale652/repos",
      "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ale652/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ale652/CV-APP",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Ale652/CV-APP",
    "forks_url": "https://api.github.com/repos/Ale652/CV-APP/forks",
    "keys_url": "https://api.github.com/repos/Ale652/CV-APP/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ale652/CV-APP/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ale652/CV-APP/teams",
    "hooks_url": "https://api.github.com/repos/Ale652/CV-APP/hooks",
    "issue_events_url": "https://api.github.com/repos/Ale652/CV-APP/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ale652/CV-APP/events",
    "assignees_url": "https://api.github.com/repos/Ale652/CV-APP/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ale652/CV-APP/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ale652/CV-APP/tags",
    "blobs_url": "https://api.github.com/repos/Ale652/CV-APP/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ale652/CV-APP/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ale652/CV-APP/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ale652/CV-APP/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ale652/CV-APP/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ale652/CV-APP/languages",
    "stargazers_url": "https://api.github.com/repos/Ale652/CV-APP/stargazers",
    "contributors_url": "https://api.github.com/repos/Ale652/CV-APP/contributors",
    "subscribers_url": "https://api.github.com/repos/Ale652/CV-APP/subscribers",
    "subscription_url": "https://api.github.com/repos/Ale652/CV-APP/subscription",
    "commits_url": "https://api.github.com/repos/Ale652/CV-APP/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ale652/CV-APP/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ale652/CV-APP/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ale652/CV-APP/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ale652/CV-APP/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ale652/CV-APP/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ale652/CV-APP/merges",
    "archive_url": "https://api.github.com/repos/Ale652/CV-APP/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ale652/CV-APP/downloads",
    "issues_url": "https://api.github.com/repos/Ale652/CV-APP/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ale652/CV-APP/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ale652/CV-APP/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ale652/CV-APP/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ale652/CV-APP/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ale652/CV-APP/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ale652/CV-APP/deployments",
    "created_at": "2022-04-13T19:09:29Z",
    "updated_at": "2022-04-13T19:18:00Z",
    "pushed_at": "2022-04-13T19:16:34Z",
    "git_url": "git://github.com/Ale652/CV-APP.git",
    "ssh_url": "git@github.com:Ale652/CV-APP.git",
    "clone_url": "https://github.com/Ale652/CV-APP.git",
    "svn_url": "https://github.com/Ale652/CV-APP",
    "homepage": null,
    "size": 970,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 466851785,
    "node_id": "R_kgDOG9OXyQ",
    "name": "devmind-m3",
    "full_name": "Ale652/devmind-m3",
    "private": false,
    "owner": {
      "login": "Ale652",
      "id": 8323240,
      "node_id": "MDQ6VXNlcjgzMjMyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ale652",
      "html_url": "https://github.com/Ale652",
      "followers_url": "https://api.github.com/users/Ale652/followers",
      "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
      "organizations_url": "https://api.github.com/users/Ale652/orgs",
      "repos_url": "https://api.github.com/users/Ale652/repos",
      "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ale652/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ale652/devmind-m3",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Ale652/devmind-m3",
    "forks_url": "https://api.github.com/repos/Ale652/devmind-m3/forks",
    "keys_url": "https://api.github.com/repos/Ale652/devmind-m3/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ale652/devmind-m3/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ale652/devmind-m3/teams",
    "hooks_url": "https://api.github.com/repos/Ale652/devmind-m3/hooks",
    "issue_events_url": "https://api.github.com/repos/Ale652/devmind-m3/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ale652/devmind-m3/events",
    "assignees_url": "https://api.github.com/repos/Ale652/devmind-m3/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ale652/devmind-m3/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ale652/devmind-m3/tags",
    "blobs_url": "https://api.github.com/repos/Ale652/devmind-m3/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ale652/devmind-m3/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ale652/devmind-m3/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ale652/devmind-m3/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ale652/devmind-m3/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ale652/devmind-m3/languages",
    "stargazers_url": "https://api.github.com/repos/Ale652/devmind-m3/stargazers",
    "contributors_url": "https://api.github.com/repos/Ale652/devmind-m3/contributors",
    "subscribers_url": "https://api.github.com/repos/Ale652/devmind-m3/subscribers",
    "subscription_url": "https://api.github.com/repos/Ale652/devmind-m3/subscription",
    "commits_url": "https://api.github.com/repos/Ale652/devmind-m3/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ale652/devmind-m3/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ale652/devmind-m3/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ale652/devmind-m3/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ale652/devmind-m3/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ale652/devmind-m3/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ale652/devmind-m3/merges",
    "archive_url": "https://api.github.com/repos/Ale652/devmind-m3/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ale652/devmind-m3/downloads",
    "issues_url": "https://api.github.com/repos/Ale652/devmind-m3/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ale652/devmind-m3/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ale652/devmind-m3/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ale652/devmind-m3/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ale652/devmind-m3/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ale652/devmind-m3/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ale652/devmind-m3/deployments",
    "created_at": "2022-03-06T20:44:15Z",
    "updated_at": "2022-03-06T20:51:01Z",
    "pushed_at": "2022-05-24T15:58:54Z",
    "git_url": "git://github.com/Ale652/devmind-m3.git",
    "ssh_url": "git@github.com:Ale652/devmind-m3.git",
    "clone_url": "https://github.com/Ale652/devmind-m3.git",
    "svn_url": "https://github.com/Ale652/devmind-m3",
    "homepage": null,
    "size": 82457,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 37719035,
    "node_id": "MDEwOlJlcG9zaXRvcnkzNzcxOTAzNQ==",
    "name": "google_pacman",
    "full_name": "Ale652/google_pacman",
    "private": false,
    "owner": {
      "login": "Ale652",
      "id": 8323240,
      "node_id": "MDQ6VXNlcjgzMjMyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ale652",
      "html_url": "https://github.com/Ale652",
      "followers_url": "https://api.github.com/users/Ale652/followers",
      "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
      "organizations_url": "https://api.github.com/users/Ale652/orgs",
      "repos_url": "https://api.github.com/users/Ale652/repos",
      "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ale652/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ale652/google_pacman",
    "description": "Play Google Pacman",
    "fork": true,
    "url": "https://api.github.com/repos/Ale652/google_pacman",
    "forks_url": "https://api.github.com/repos/Ale652/google_pacman/forks",
    "keys_url": "https://api.github.com/repos/Ale652/google_pacman/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ale652/google_pacman/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ale652/google_pacman/teams",
    "hooks_url": "https://api.github.com/repos/Ale652/google_pacman/hooks",
    "issue_events_url": "https://api.github.com/repos/Ale652/google_pacman/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ale652/google_pacman/events",
    "assignees_url": "https://api.github.com/repos/Ale652/google_pacman/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ale652/google_pacman/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ale652/google_pacman/tags",
    "blobs_url": "https://api.github.com/repos/Ale652/google_pacman/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ale652/google_pacman/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ale652/google_pacman/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ale652/google_pacman/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ale652/google_pacman/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ale652/google_pacman/languages",
    "stargazers_url": "https://api.github.com/repos/Ale652/google_pacman/stargazers",
    "contributors_url": "https://api.github.com/repos/Ale652/google_pacman/contributors",
    "subscribers_url": "https://api.github.com/repos/Ale652/google_pacman/subscribers",
    "subscription_url": "https://api.github.com/repos/Ale652/google_pacman/subscription",
    "commits_url": "https://api.github.com/repos/Ale652/google_pacman/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ale652/google_pacman/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ale652/google_pacman/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ale652/google_pacman/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ale652/google_pacman/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ale652/google_pacman/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ale652/google_pacman/merges",
    "archive_url": "https://api.github.com/repos/Ale652/google_pacman/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ale652/google_pacman/downloads",
    "issues_url": "https://api.github.com/repos/Ale652/google_pacman/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ale652/google_pacman/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ale652/google_pacman/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ale652/google_pacman/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ale652/google_pacman/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ale652/google_pacman/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ale652/google_pacman/deployments",
    "created_at": "2015-06-19T11:50:38Z",
    "updated_at": "2015-06-19T11:50:38Z",
    "pushed_at": "2014-03-12T00:14:01Z",
    "git_url": "git://github.com/Ale652/google_pacman.git",
    "ssh_url": "git@github.com:Ale652/google_pacman.git",
    "clone_url": "https://github.com/Ale652/google_pacman.git",
    "svn_url": "https://github.com/Ale652/google_pacman",
    "homepage": "http://macek.github.com/google_pacman",
    "size": 369,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": false,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 174878672,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNzQ4Nzg2NzI=",
    "name": "json-simple",
    "full_name": "Ale652/json-simple",
    "private": false,
    "owner": {
      "login": "Ale652",
      "id": 8323240,
      "node_id": "MDQ6VXNlcjgzMjMyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ale652",
      "html_url": "https://github.com/Ale652",
      "followers_url": "https://api.github.com/users/Ale652/followers",
      "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
      "organizations_url": "https://api.github.com/users/Ale652/orgs",
      "repos_url": "https://api.github.com/users/Ale652/repos",
      "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ale652/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ale652/json-simple",
    "description": "A simple Java toolkit for JSON. You can use json-simple to encode or decode JSON text.",
    "fork": true,
    "url": "https://api.github.com/repos/Ale652/json-simple",
    "forks_url": "https://api.github.com/repos/Ale652/json-simple/forks",
    "keys_url": "https://api.github.com/repos/Ale652/json-simple/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ale652/json-simple/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ale652/json-simple/teams",
    "hooks_url": "https://api.github.com/repos/Ale652/json-simple/hooks",
    "issue_events_url": "https://api.github.com/repos/Ale652/json-simple/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ale652/json-simple/events",
    "assignees_url": "https://api.github.com/repos/Ale652/json-simple/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ale652/json-simple/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ale652/json-simple/tags",
    "blobs_url": "https://api.github.com/repos/Ale652/json-simple/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ale652/json-simple/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ale652/json-simple/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ale652/json-simple/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ale652/json-simple/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ale652/json-simple/languages",
    "stargazers_url": "https://api.github.com/repos/Ale652/json-simple/stargazers",
    "contributors_url": "https://api.github.com/repos/Ale652/json-simple/contributors",
    "subscribers_url": "https://api.github.com/repos/Ale652/json-simple/subscribers",
    "subscription_url": "https://api.github.com/repos/Ale652/json-simple/subscription",
    "commits_url": "https://api.github.com/repos/Ale652/json-simple/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ale652/json-simple/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ale652/json-simple/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ale652/json-simple/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ale652/json-simple/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ale652/json-simple/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ale652/json-simple/merges",
    "archive_url": "https://api.github.com/repos/Ale652/json-simple/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ale652/json-simple/downloads",
    "issues_url": "https://api.github.com/repos/Ale652/json-simple/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ale652/json-simple/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ale652/json-simple/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ale652/json-simple/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ale652/json-simple/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ale652/json-simple/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ale652/json-simple/deployments",
    "created_at": "2019-03-10T20:43:35Z",
    "updated_at": "2019-03-10T20:43:37Z",
    "pushed_at": "2019-03-04T23:23:32Z",
    "git_url": "git://github.com/Ale652/json-simple.git",
    "ssh_url": "git@github.com:Ale652/json-simple.git",
    "clone_url": "https://github.com/Ale652/json-simple.git",
    "svn_url": "https://github.com/Ale652/json-simple",
    "homepage": "",
    "size": 376,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": false,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 435297385,
    "node_id": "R_kgDOGfIcaQ",
    "name": "OOP-Game",
    "full_name": "Ale652/OOP-Game",
    "private": false,
    "owner": {
      "login": "Ale652",
      "id": 8323240,
      "node_id": "MDQ6VXNlcjgzMjMyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ale652",
      "html_url": "https://github.com/Ale652",
      "followers_url": "https://api.github.com/users/Ale652/followers",
      "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
      "organizations_url": "https://api.github.com/users/Ale652/orgs",
      "repos_url": "https://api.github.com/users/Ale652/repos",
      "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ale652/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ale652/OOP-Game",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Ale652/OOP-Game",
    "forks_url": "https://api.github.com/repos/Ale652/OOP-Game/forks",
    "keys_url": "https://api.github.com/repos/Ale652/OOP-Game/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ale652/OOP-Game/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ale652/OOP-Game/teams",
    "hooks_url": "https://api.github.com/repos/Ale652/OOP-Game/hooks",
    "issue_events_url": "https://api.github.com/repos/Ale652/OOP-Game/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ale652/OOP-Game/events",
    "assignees_url": "https://api.github.com/repos/Ale652/OOP-Game/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ale652/OOP-Game/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ale652/OOP-Game/tags",
    "blobs_url": "https://api.github.com/repos/Ale652/OOP-Game/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ale652/OOP-Game/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ale652/OOP-Game/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ale652/OOP-Game/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ale652/OOP-Game/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ale652/OOP-Game/languages",
    "stargazers_url": "https://api.github.com/repos/Ale652/OOP-Game/stargazers",
    "contributors_url": "https://api.github.com/repos/Ale652/OOP-Game/contributors",
    "subscribers_url": "https://api.github.com/repos/Ale652/OOP-Game/subscribers",
    "subscription_url": "https://api.github.com/repos/Ale652/OOP-Game/subscription",
    "commits_url": "https://api.github.com/repos/Ale652/OOP-Game/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ale652/OOP-Game/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ale652/OOP-Game/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ale652/OOP-Game/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ale652/OOP-Game/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ale652/OOP-Game/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ale652/OOP-Game/merges",
    "archive_url": "https://api.github.com/repos/Ale652/OOP-Game/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ale652/OOP-Game/downloads",
    "issues_url": "https://api.github.com/repos/Ale652/OOP-Game/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ale652/OOP-Game/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ale652/OOP-Game/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ale652/OOP-Game/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ale652/OOP-Game/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ale652/OOP-Game/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ale652/OOP-Game/deployments",
    "created_at": "2021-12-05T22:48:43Z",
    "updated_at": "2021-12-05T22:54:29Z",
    "pushed_at": "2021-12-05T22:54:27Z",
    "git_url": "git://github.com/Ale652/OOP-Game.git",
    "ssh_url": "git@github.com:Ale652/OOP-Game.git",
    "clone_url": "https://github.com/Ale652/OOP-Game.git",
    "svn_url": "https://github.com/Ale652/OOP-Game",
    "homepage": null,
    "size": 7,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 39303364,
    "node_id": "MDEwOlJlcG9zaXRvcnkzOTMwMzM2NA==",
    "name": "ShopN",
    "full_name": "Ale652/ShopN",
    "private": false,
    "owner": {
      "login": "Ale652",
      "id": 8323240,
      "node_id": "MDQ6VXNlcjgzMjMyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ale652",
      "html_url": "https://github.com/Ale652",
      "followers_url": "https://api.github.com/users/Ale652/followers",
      "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
      "organizations_url": "https://api.github.com/users/Ale652/orgs",
      "repos_url": "https://api.github.com/users/Ale652/repos",
      "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ale652/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ale652/ShopN",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Ale652/ShopN",
    "forks_url": "https://api.github.com/repos/Ale652/ShopN/forks",
    "keys_url": "https://api.github.com/repos/Ale652/ShopN/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ale652/ShopN/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ale652/ShopN/teams",
    "hooks_url": "https://api.github.com/repos/Ale652/ShopN/hooks",
    "issue_events_url": "https://api.github.com/repos/Ale652/ShopN/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ale652/ShopN/events",
    "assignees_url": "https://api.github.com/repos/Ale652/ShopN/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ale652/ShopN/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ale652/ShopN/tags",
    "blobs_url": "https://api.github.com/repos/Ale652/ShopN/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ale652/ShopN/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ale652/ShopN/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ale652/ShopN/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ale652/ShopN/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ale652/ShopN/languages",
    "stargazers_url": "https://api.github.com/repos/Ale652/ShopN/stargazers",
    "contributors_url": "https://api.github.com/repos/Ale652/ShopN/contributors",
    "subscribers_url": "https://api.github.com/repos/Ale652/ShopN/subscribers",
    "subscription_url": "https://api.github.com/repos/Ale652/ShopN/subscription",
    "commits_url": "https://api.github.com/repos/Ale652/ShopN/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ale652/ShopN/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ale652/ShopN/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ale652/ShopN/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ale652/ShopN/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ale652/ShopN/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ale652/ShopN/merges",
    "archive_url": "https://api.github.com/repos/Ale652/ShopN/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ale652/ShopN/downloads",
    "issues_url": "https://api.github.com/repos/Ale652/ShopN/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ale652/ShopN/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ale652/ShopN/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ale652/ShopN/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ale652/ShopN/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ale652/ShopN/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ale652/ShopN/deployments",
    "created_at": "2015-07-18T15:45:39Z",
    "updated_at": "2015-07-18T15:50:13Z",
    "pushed_at": "2015-07-18T15:50:13Z",
    "git_url": "git://github.com/Ale652/ShopN.git",
    "ssh_url": "git@github.com:Ale652/ShopN.git",
    "clone_url": "https://github.com/Ale652/ShopN.git",
    "svn_url": "https://github.com/Ale652/ShopN",
    "homepage": null,
    "size": 112,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 443883148,
    "node_id": "R_kgDOGnUejA",
    "name": "SIIT_SCOALA_INFORMALA2022",
    "full_name": "Ale652/SIIT_SCOALA_INFORMALA2022",
    "private": false,
    "owner": {
      "login": "Ale652",
      "id": 8323240,
      "node_id": "MDQ6VXNlcjgzMjMyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8323240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ale652",
      "html_url": "https://github.com/Ale652",
      "followers_url": "https://api.github.com/users/Ale652/followers",
      "following_url": "https://api.github.com/users/Ale652/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ale652/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ale652/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ale652/subscriptions",
      "organizations_url": "https://api.github.com/users/Ale652/orgs",
      "repos_url": "https://api.github.com/users/Ale652/repos",
      "events_url": "https://api.github.com/users/Ale652/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ale652/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ale652/SIIT_SCOALA_INFORMALA2022",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022",
    "forks_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/forks",
    "keys_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/teams",
    "hooks_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/hooks",
    "issue_events_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/events",
    "assignees_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/tags",
    "blobs_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/languages",
    "stargazers_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/stargazers",
    "contributors_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/contributors",
    "subscribers_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/subscribers",
    "subscription_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/subscription",
    "commits_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/merges",
    "archive_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/downloads",
    "issues_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ale652/SIIT_SCOALA_INFORMALA2022/deployments",
    "created_at": "2022-01-02T22:25:55Z",
    "updated_at": "2022-01-02T22:31:43Z",
    "pushed_at": "2022-01-26T18:56:27Z",
    "git_url": "git://github.com/Ale652/SIIT_SCOALA_INFORMALA2022.git",
    "ssh_url": "git@github.com:Ale652/SIIT_SCOALA_INFORMALA2022.git",
    "clone_url": "https://github.com/Ale652/SIIT_SCOALA_INFORMALA2022.git",
    "svn_url": "https://github.com/Ale652/SIIT_SCOALA_INFORMALA2022",
    "homepage": null,
    "size": 221,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 5,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 5,
    "watchers": 0,
    "default_branch": "main"
  }
]
;


export default App;
